services:
  app:
    image: node:24
    container_name: express_app
    user: "${USERID:-1000}:${USERGROUP:-1000}"
    working_dir: /var/www/html
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    command: npm run dev
    volumes:
      - .:/var/www/html
    networks:
      - express_net
  
  db:
    image: mysql:latest
    container_name: express_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_NAME:-docker_mastery}
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    networks:
      - express_net
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local

networks:
  express_net:
    driver: bridge